# Generated by Django 3.0.2 on 2020-01-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='post_images/'),
        ),
    ]
