# Generated by Django 3.0.2 on 2020-01-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='post_images/default_profile_pic.jpg', upload_to='post_images/'),
        ),
    ]
