# Generated by Django 3.0.2 on 2020-01-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_like_number_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='number_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
