# Generated by Django 3.0.2 on 2020-01-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20200130_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(),
        ),
    ]
